#!/bin/bash

complete -cf sudo
complete -cf which

export VISUAL=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

alias ls='ls -h --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias df='df -Th'
alias mkdir='mkdir -p -m 775'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias df='df -Th'
alias cdgit='cd /data/git_repo'
alias cdwork='cd /data/workspace'
alias cdyocto='cd /data/yocto'

function GitLocalConfig
{
	if [[ ${1} = "luck.hoang" ]]; then
		git config user.email "luck.hoang@styl.solutions"
		git config user.name "Luck Hoang"
	elif [[ ${1} = "huyht1205" ]]; then
		git config user.email "huyht1205@gmail.com"
		git config user.name "Hoang Trung Huy"
	else
		printf "\e[31mERROR: please enter name \"huyht1205\" or \"luck.hoang\"\e[0m\n"
	fi
}


function CloneMyRepo
{
	DIR=${2}
	git clone https://github.com/huyht1205/${1} ${DIR}
}

function addAlias
{
	vim ~/.bash_aliases ; source ~/.bash_aliases
	updateGit
}

function addAliasPrivate
{
	vim ~/.bash_aliases_$(uname) ; source ~/.bash_aliases_$(uname)
	updateGit
}

function updateGit
{
	CURRENT_PATH=$(pwd)
	cdgit
	cd scripts
	git add -A
	git commit --amend
	cd ${CURRENT_PATH}
}

function DoCrossConf
{
	#CROSS_COMPILER_PATH=/data/workspace/tools/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabi/bin/
	export CROSS_COMPILE=${CROSS_COMPILER_PATH}arm-linux-gnueabi-
	export ARCH=arm
}

source ~/.bash_aliases_$(uname)

