#!/bin/bash

ROOT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
GIT_REPO="/data/git_repo"
source ${ROOT_DIR}/utils.sh

complete -cf sudo
complete -cf which

export VISUAL=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

alias ls='ls -h --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias df='df -Th'
alias mkdir='mkdir -p -m 775'
alias grep='grep --color=auto --exclude=tags'
alias egrep='egrep --color=auto --exclude=tags -n'
alias df='df -Th'
alias make='make -j${CPU_CORE}'
alias cdgit="cd ${GIT_REPO}"
alias cdwork='cd /data/workspace'
alias cdbuildroot='cd /data/buildroot'
alias dkc='docker container ls -a'

SSH_OPTS="-4"
alias ssh='ssh ${SSH_OPTS}'
SSHFS_OPTS="-o cache=yes -o kernel_cache -o compression=no"
alias sshfs='sshfs ${SSHFS_OPTS}'

TEMPLATE_PATH="/data/git_repo/env_scripts/template"
SDK_PATH="/data/sdk"
NRF_SDK="${SDK_PATH}/nRF/bin"
ARM_NONE_EABI_GCC="${SDK_PATH}/arm-none-eabi-gcc/bin"
DEV_SCRIPTS="/data/git_repo/env_scripts/dev-scripts"
TOOLS_PATH="/data/git_repo/env_scripts/utils"
export PATH=${PATH}:${NRF_SDK}:${ARM_NONE_EABI_GCC}:${DEV_SCRIPTS}
export PATH=${PATH}:${TEMPLATE_PATH}:${TOOLS_PATH}

function addAlias
{
	vim ~/.bash_aliases ; source ~/.bash_aliases
}

function addAliasPrivate
{
	vim ~/.bash_aliases_$(uname) ; source ~/.bash_aliases_$(uname)
}

function Template_cmake()
{
    _OUTPUT=${PWD}/CMakeLists.txt
    _TYPE=${1}

	if [[ -z ${_TYPE} ]]; then
		echo "Usage: ${0} <lib|bin>"
		return -1
	fi

    _CMAKE_TEMPLATE_PATH=${TEMPLATE_PATH}/cmake
    cp ${_CMAKE_TEMPLATE_PATH}/CMakeLists_core.template ${_OUTPUT}
    cat ${_CMAKE_TEMPLATE_PATH}/CMakeLists_${_TYPE}.template >> ${_OUTPUT}
}

function CmakeClean()
{
    _CLEAN_LIST=(
        compile_commands.json
        CMakeCache.txt
        CMakeFiles
        cmake_install.cmake
        Makefile
        )
    rm -rf ${_CLEAN_LIST[@]}
}

function Template_bash()
{
	if [[ -z ${1} ]]; then
		echo "Usage: ${0} <script name>"
		return -1
	fi

    _BASH_TEMPLATE_PATH=${TEMPLATE_PATH}/bash
    cp ${_BASH_TEMPLATE_PATH}/Bash_script.template ${1}
}

source ~/.bash_aliases_$(uname)
