#!/bin/bash
export PS1='\[\033[37;1m\]\w\[\033[0m\]\$ '

USB_SERIAL=/dev/tty.usbserial-AL01FJMD

alias GotoWork='ssh huyht@HHPC.local'
alias cdenv='cd ~/Desktop/workspace'

alias ConnectSerial='picocom -b 115200 '${USB_SERIAL}
alias sshRefresh='rm ~/.ssh/known_host*'

echo ---Finished path edit---
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/findutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/coreutils/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

source ~/.git-completion.bash
