#!/bin/bash
export PS1='\[\033[37;1m\]\w\[\033[0m\]\$ '

USB_SERIAL=/dev/tty.usbserial-AL01FJMD

alias GotoWork='ssh root@$(cat ~/.LINUX_IP)'
alias cdwork='cd ~/Desktop/workspace'
alias cdgit='cd ~/Desktop/workspace/git_repo'
alias mktemp=/usr/bin/mktemp

alias ConnectBoard='ssh root@192.168.100.4'
alias sshRefresh='rm ~/.ssh/known_host*'

echo ---Finished path edit---
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/findutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/coreutils/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

function sshUpdate
{
	echo $1 > ~/.LINUX_IP
}

function DoCrossConf
{
	export MACHINE=arm-linux-gnueabihf
	export CROSS_ROOT=/usr/local/linaro/${MACHINE}/${MACHINE}

	export CROSS_COMPILE=${CROSS_ROOT}/../bin/${MACHINE}-
	export CROSS_LIB=${CROSS_ROOT}/lib32
	export CROSS_INCLUDE=${CROSS_ROOT}/libc/usr/include
	
}

function mountShareNFS
{
	SHARE_POINT=/tftpboot
	SHARE_DES=/Users/huytrunghoang/Desktop/workspace/nfs
	sudo mount -t nfs -o resvport,rw 192.168.100.3:${SHARE_POINT} ${SHARE_DES}
}

source ~/.git-completion.bash
