#!/bin/bash
export PS1='\[\033[37;1m\]\w\[\033[0m\]\$ '
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/linaro/arm-linux-gnueabihf/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

#USB_SERIAL=/dev/tty.usbserial-AL01FJMD
USB_SERIAL=/dev/tty.SLAB_USBtoUART

alias Serial='picocom -b 115200 $USB_SERIAL'
alias sshRefresh='rm ~/.ssh/known_host*'
alias picocom='picocom -e q'

LAPTOP_IP=lh-asuspc.local
LAPTOP_ACC=luckhoang
VM_IP=vm.local
VM_ACC=root
PC_IP=lh-pc.local
PC_ACC=luckhoang
MOUNTPOINT=/data/mountPoint
alias GotoLaptop='ssh ${LAPTOP_ACC}@${LAPTOP_IP}'
alias MountLaptop='sshfs ${LAPTOP_ACC}@${LAPTOP_IP}:/ ${MOUNTPOINT}/lh-asuspc'
alias GotoVM='ssh ${VM_ACC}@${VM_IP}'
alias MountVM='sshfs ${VM_ACC}@${VM_IP}:/ ${MOUNTPOINT}/vm'
alias GotoPC='ssh luckhoang@${PC_IP}'
alias MountPC='sshfs luckhoang@${PC_IP}:/ ${MOUNTPOINT}/pc'

export PATH="/usr/local/bin:$PATH"
echo ---Finished path edit---

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

source ~/.git-completion.bash

if [ -f /usr/local/etc/bash_completion ]; then  
. /usr/local/etc/bash_completion
fi  
