#!/bin/bash

USB_SERIAL=/dev/tty.usbserial-AL01FJMD

alias GotoWork='ssh huyht@HHPC.local'
alias cdenv='cd ~/Desktop/PROGRAMMING'
alias ConnectSerial='picocom -b 115200 '${USB_SERIAL}
alias sshRefresh='rm ~/.ssh/knownhost*'

echo ---Finished path edit---
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/findutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/coreutils/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
