#!/bin/bash
export PS1='\[\033[31;1m\]\w\[\033[0m\]\$ '

alias cdenv='cd /data'
alias Rebuild='bitbake -c cleansstate beginner-tutorials && bitbake beginner-tutorials'

function DoSB2Conf {
	sb2-init -n -c /usr/bin/qemu-arm $1 /usr/bin/arm-linux-gnueabihf-gcc
}
